name: Build and Package Grafana Plugin (ARM)

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64 # 指定目标平台

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend (Mage)
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile # 假设你的后端 Dockerfile 在这里
          platforms: linux/arm64
          build-args: |
            GOOS=linux
            GOARCH=arm64
          outputs: |
            type=local,dest=./dist/backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 或者你需要的 Node.js 版本

      - name: Install Frontend Dependencies
        working-directory: ./src # 假设你的前端代码在 src 目录
        run: npm install

      - name: Build Frontend (npm)
        working-directory: ./src
        run: npm run build

      - name: Create Distribution Directory
        run: mkdir -p dist/frontend

      - name: Copy Frontend Artifacts
        run: |
          cp -r src/dist/* dist/frontend/ # 假设 npm run build 的输出在 src/dist 目录

      - name: Package Distribution
        run: |
          tar -czvf plugin.tar.gz dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-dist
          path: plugin.tar.gz
