name: Build and Package Grafana Plugin (ARM)

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64 # 指定目标平台

      - name: Set up Go for ARM
        uses: actions/setup-go@v3
        with:
          go-version: '1.18' # 或者你需要的 Go 版本

      - name: Install Mage
        run: |
          go install github.com/magefile/mage@latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 或者你需要的 Node.js 版本

      - name: Install Frontend Dependencies
        working-directory: ./src
        run: npm install

      - name: Build Frontend (npm)
        working-directory: ./src
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Build Backend (Mage) for ARM64
        run: |
          GOOS=linux GOARCH=arm64 mage build # 假设你的 magefile 中默认的 build 任务会构建后端
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Package Distribution
        run: |
          tar -czvf plugin.tar.gz dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-dist
          path: plugin.tar.gz
